"use client";
import { useEffect, useState } from "react";
import { ArrowUpRight, Menu, Moon, Sun, X } from "lucide-react";
export default function HeaderControls() {
  const [dark,setDark]=useState(false); const [open,setOpen]=useState(false);
  useEffect(()=>{ setDark(document.documentElement.dataset.theme==="dark"); const close=(event:KeyboardEvent)=>event.key==="Escape"&&setOpen(false); window.addEventListener("keydown",close); return()=>window.removeEventListener("keydown",close); },[]);
  function toggleTheme(){ const next=!dark; setDark(next); document.documentElement.dataset.theme=next?"dark":"light"; document.documentElement.style.colorScheme=next?"dark":"light"; localStorage.setItem("flytek-theme",next?"dark":"light"); }
  return <div className="flytek-controls"><a className="flytek-header-contact" href="/#contacto">Hablemos <ArrowUpRight size={16}/></a><button className="flytek-icon-button" onClick={toggleTheme} aria-label={dark?"Activar modo claro":"Activar modo oscuro"} title={dark?"Modo claro":"Modo oscuro"}>{dark?<Sun size={18}/>:<Moon size={18}/>}</button><button className="flytek-menu-button" onClick={()=>setOpen(!open)} aria-label={open ? "Cerrar menú" : "Abrir menú"} aria-expanded={open} aria-controls="flytek-menu"><span>Menú</span>{open?<X size={20}/>:<Menu size={20}/>}</button><div className="flytek-menu" id="flytek-menu" hidden={!open}><div className="flytek-menu-heading"><span>NAVEGACIÓN</span><small>FLYTEK / MX</small></div><nav aria-label="Todas las secciones" onClick={()=>setOpen(false)}><a href="/"><b>01</b><span>Inicio</span><ArrowUpRight/></a><a href="/#empresa"><b>02</b><span>Quiénes somos</span><ArrowUpRight/></a><a href="/#drones"><b>03</b><span>Plataformas</span><ArrowUpRight/></a><a href="/#sectores"><b>04</b><span>Sectores</span><ArrowUpRight/></a><a href="/fenix"><b>05</b><span>FÉNIX</span><ArrowUpRight/></a><a href="/orion-mx"><b>06</b><span>ORION MX</span><ArrowUpRight/></a><a href="/vega"><b>07</b><span>VEGA</span><ArrowUpRight/></a><a href="/#contacto"><b>08</b><span>Contacto</span><ArrowUpRight/></a></nav></div>{open&&<button className="flytek-menu-backdrop" aria-label="Cerrar menú" onClick={()=>setOpen(false)}/>}</div>;
}

