/** Editable editorial copy. All marketing headlines are provisional. */
export const vegaCopy = {
  flytek: "FLYTEK",
  innovations: "INNOVATIONS",
  plataformas: "Plataformas",
  fenix_proximamente: "FÉNIX · Próximamente",
  vega: "VEGA ↗",
  orion_proximamente: "ORION · Próximamente",
  sectores: "Sectores",
  servicios: "Servicios",
  capacitaciones: "Capacitaciones",
  hablemos: "Hablemos",
  plataformas_tecnologia_nuevas_perspectivas:
    "Plataformas. Tecnología. Nuevas perspectivas.",
  volver_arriba: "VOLVER ARRIBA ↑",
  flytek_innovations: "Flytek Innovations",
  propuesta_de_producto_contenido_tecnico_pendiente_de_validacion:
    "Propuesta de producto · Contenido técnico pendiente de validación",
  flytek_plataformas: "FLYTEK / PLATAFORMAS",
  label_01_vega: "VEGA",
  vega_2: "VEGA",
  plataforma_vega: "PLATAFORMA VEGA",
  vista_general: "VISTA GENERAL",
  conocer_vega: "CONOCER VEGA",
  diseno_tecnologia_integracion: "DISEÑO · TECNOLOGÍA · INTEGRACIÓN",
  saltar_al_contenido: "Saltar al contenido",
  label_01_conoce_vega: "01 / CONOCE VEGA",
  el_producto_en_primer_plano: "EL PRODUCTO, EN PRIMER PLANO",
  una_plataforma: "Una plataforma.",
  cada_detalle_a_la_vista: "Cada detalle, a la vista.",
  observa_gira_descubre: "OBSERVA. GIRA. DESCUBRE.",
  conoce_vega: "Conoce VEGA.",
  desde_todos_los_angulos: "Desde todos los ángulos.",
  explora_el_modelo_y_acercate_a_sus_detalles:
    "Explora el modelo y acércate a sus detalles.",
  explorar_en_3d: "EXPLORAR EN 3D",
  vega_en_detalle: "VEGA EN DETALLE",
  de_la_vista_general_al_detalle: "DE LA VISTA GENERAL AL DETALLE ↓",
  el_siguiente_paso_flytek: "EL SIGUIENTE PASO / FLYTEK",
  label_06_payloads_e_integracion: "06 / PAYLOADS E INTEGRACIÓN",
  configuracion_por_definir: "CONFIGURACIÓN POR DEFINIR",
  un_punto_de_partida: "Un punto de partida.",
  tu_configuracion: "Tu configuración.",
  explora_la_integracion: "EXPLORA LA INTEGRACIÓN",
  compatibilidad_y_ubicacion_de_integracion_pendientes_de_confirmar:
    "Compatibilidad y ubicación de integración pendientes de confirmar.",
  integracion: "INTEGRACIÓN",
  por_definir: "SEGÚN CONFIGURACIÓN",
  label_03_diseno_y_construccion: "03 / DISEÑO Y CONSTRUCCIÓN",
  de_cerca: "De cerca.",
  sin_perder: "Sin perder",
  el_conjunto: "el conjunto.",
  vega_detalle_de_la_estructura: "VEGA / DETALLE DE LA ESTRUCTURA",
  label_01_detalle_por_definir: "01 — ESTRUCTURA",
  label_04_rendimiento: "04 / RENDIMIENTO",
  datos_tecnicos: "DATOS TÉCNICOS",
  la_capacidad: "La capacidad.",
  en_perspectiva: "En perspectiva.",
  label_05_tecnologia: "05 / TECNOLOGÍA",
  una_vision: "Una visión",
  del_sistema: "del sistema.",
  plataforma: "PLATAFORMA",
  label_07_aplicaciones: "07 / APLICACIONES",
  producto_operacion: "PRODUCTO → OPERACIÓN",
  el_siguiente_contexto: "El siguiente contexto.",
  aplicaciones_sectores_y_fotografias_de_operacion_por_definir:
    "Define con Flytek el equipo y la carga útil para tu operación. Imágenes ilustrativas.",
  vega_3: "/ VEGA",
  ver_sector: "VER SECTOR ↗",
  sector_por_definir: "SECTOR POR DEFINIR ↗",
  label_08_especificaciones: "08 / ESPECIFICACIONES",
  especificaciones: "Especificaciones",
  tecnicas: "técnicas.",
  informacion_tecnica_pendiente_de_validacion:
    "Valores de referencia del sitio Flytek. Confirma la configuración vigente con nuestro equipo.",
  label_02_explorador_interactivo: "02 / EXPLORADOR INTERACTIVO",
  tu_punto_de_vista: "Tu punto de vista.",
  modelo_original_vega: "MODELO ORIGINAL VEGA",
  vega_3d: "VEGA / 3D",
  perspectiva_libre: "PERSPECTIVA LIBRE",
  cargando_modelo: "CARGANDO MODELO",
  el_visor_3d_no_esta_disponible: "El visor 3D no está disponible.",
  puedes_continuar_explorando_la_pagina:
    "Puedes continuar explorando la página.",
  reintentar_carga: "Reintentar carga",
  volver_a_vista_general: "VOLVER A VISTA GENERAL ↗",
  puntos_de_referencia_provisionales_componentes_por_confirmar:
    "Puntos de referencia provisionales. Componentes por confirmar.",
  tambien_puedes_explorar_vega_usando_los_botones_de:
    "También puedes explorar VEGA usando los botones de vista y zoom. En el lienzo activo usa flechas para girar, + o − para acercar o alejar y Escape para salir.",
  finalizar_interaccion_3d: "Finalizar interacción 3D",
  flytek_atencion_al_cliente: "FLYTEK / ATENCIÓN AL CLIENTE",
  de_tu_operacion: "de tu operación.",
  canal_de_contacto_por_definir: "[CANAL DE CONTACTO POR DEFINIR]",
  esta_pagina_se_conectara_con_la_atencion_general:
    "Esta página se conectará con la atención general de Flytek.",
  el_correo_telefono_o_formulario_oficial_aun_no:
    "El correo, teléfono o formulario oficial aún no se han proporcionado.",
  volver_a_vega: "← VOLVER A VEGA",
} as const;
